name: Secret Expiry Notifier

on:
  schedule:
    - cron: '0 11 * * *'  # Runs every day at 11 AM UTC (6 or 7 AM EST depending on DST)
  workflow_dispatch:

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run notifier script
        run: python notifier.py
